### ISSUE TITLE
프론트엔드 초기 세팅

### ISSUE THREAD

**Issue by wlgus3** [codestates-seb/seb42_main_029#2]
## 만들고자 하는 기능
초기 셋팅

<br>  

## 기능의 설명
본격적인 페이지 개발 전 프레임워크 제작 

<br> 

## Todo  
1. [x] react-create-app
2. [ ] header, footer 간단하게 제작
3. [x] 각종 필수 라이브러리 install

<br> 

## Issue

<br> 

## 기타사항

<br>
