### ISSUE TITLE
[ORD01] 상품 상세 페이지 

### ISSUE THREAD

**Issue by Ktuna95** [codestates-seb/seb42_main_029#20]
## 만들고자 하는 기능
상품(상품명, 가격, 메인 이미지, 상세내용은 이미지로 받기)
판매자 정보(상호명, 주소, 전화번호, 이메일)
QnA(제목, 내용)
사용후기(제목, 내용, 별점)

<br>  

## 기능의 설명
상품(상품명, 가격, 메인 이미지, 상세내용은 이미지로 받기)
판매자 정보(상호명, 주소, 전화번호, 이메일)
QnA(제목, 내용)
사용후기(제목, 내용, 별점)

<br> 

## Todo  
1. [ ] 상품명, 가격, 메인 이미지, 상세내용은 이미지로 받기
2. [ ] 판매자 정보(상호명, 주소, 전화번호, 이메일)
3. [ ] QnA(제목, 내용)
4. [ ] 사용후기(제목, 내용, 별점)

<br> 

## Issue
ex) 요청을 어떻게 할지, 데이터 모델링을 어떻게 구성할지

<br> 

## 기타사항
ex) ...

<br>
