### ISSUE TITLE
[MEM06] 회원 탈퇴

### ISSUE THREAD

**Issue by steadykyu** [codestates-seb/seb42_main_029#54]
## 만들고자 하는 기능
회원 탈퇴 기능을 구현한다.

<br>  

## 기능의 설명
< 회원 탈퇴 인증 팝업창에 비밀번호 입력, 탈퇴 확인 메세지 팝업 >

회원 탈퇴 버튼을 눌러 회원 탈퇴 진행, 탈퇴한 회원 정보는 일주일 보관
+ 회원 탈퇴 시 논리적 삭제를 위해 상태값을 ("DELETE")로 변경한다.

[Advanced] 삭제된 회원 정보는 30일동안 보관되었다가, 최종적으로 물리적으로 삭제된다.

[Advanced] 휴면 계정 처리 기능
+ 마지막 접속일자를 기준으로 60일동안 미접속 시 자동 휴면 처리한다.
+ 휴면 계정일 경우, 휴면 상태 해체 요청을 통해 휴면 계정을 해체 할 수 있다.

[Advanced] 휴면 계정 전환 전 이메일 전송
휴면 계정으로 전환되기 일주일전, 회원의 이메일로 휴면 사실을 알린다.

<br> 

## Todo  
1. [x] (Controller) stub 데이터를 이용한 핸들러 메서드 생성 및 API 명세서 작성
1. [x] 회원 삭제 메서드 생성
2. [ ] 접속일자를 계산하는 메서드 생성
3. [ ] 휴면 계정으로 처리하는 메서드 생성

<br> 

## Issue
ex) 요청을 어떻게 할지, 데이터 모델링을 어떻게 구성할지

<br> 

## 기타사항
ex) ...

<br>
